"""initial

Revision ID: e5a91459e5ad
Revises: 
Create Date: 2025-08-01 22:33:18.855126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a91459e5ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_stasiun', sa.String(length=100), nullable=False),
    sa.Column('frekuensi', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_ils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lokasi_stasiun_ils', sa.String(length=50), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('pic', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('transmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('tx1_power', sa.Float(), nullable=True),
    sa.Column('tx1_swr', sa.String(length=20), nullable=True),
    sa.Column('tx1_mod', sa.Float(), nullable=True),
    sa.Column('tx2_power', sa.Float(), nullable=True),
    sa.Column('tx2_swr', sa.String(length=20), nullable=True),
    sa.Column('tx2_mod', sa.Float(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('pic', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transmissions_gp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_ils_id', sa.Integer(), nullable=True),
    sa.Column('csb_power', sa.Float(), nullable=True),
    sa.Column('sbo_power', sa.Float(), nullable=True),
    sa.Column('sdm_80', sa.Float(), nullable=True),
    sa.Column('course_ddm', sa.Float(), nullable=True),
    sa.Column('ds_ddm', sa.Float(), nullable=True),
    sa.Column('clr_ddm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['station_ils_id'], ['station_ils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transmissions_localizer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_ils_id', sa.Integer(), nullable=True),
    sa.Column('csb_power', sa.Float(), nullable=True),
    sa.Column('sbo_power', sa.Float(), nullable=True),
    sa.Column('sdm_40', sa.Float(), nullable=True),
    sa.Column('course_ddm', sa.Float(), nullable=True),
    sa.Column('ds_ddm', sa.Float(), nullable=True),
    sa.Column('clr_ddm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['station_ils_id'], ['station_ils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transmissions_tdme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_ils_id', sa.Integer(), nullable=True),
    sa.Column('tx1_power', sa.Float(), nullable=True),
    sa.Column('spacing1', sa.String(length=20), nullable=True),
    sa.Column('delay1', sa.String(length=20), nullable=True),
    sa.Column('tx2_power', sa.Float(), nullable=True),
    sa.Column('spacing2', sa.String(length=20), nullable=True),
    sa.Column('delay2', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['station_ils_id'], ['station_ils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transmissions_tdme')
    op.drop_table('transmissions_localizer')
    op.drop_table('transmissions_gp')
    op.drop_table('transmission')
    op.drop_table('user')
    op.drop_table('station_ils')
    op.drop_table('station')
    # ### end Alembic commands ###
